// Single source of truth for the service agreement text.
// Used by the PDF generator; the on-page HTML mirrors this wording.
const CLAUSES = [
  ['1. Services', 'CallerCore will configure, deploy, and maintain an AI-powered call handling and lead management system ("the Service") for Client\'s business, as configured during onboarding. Depending on Client\'s selected plan, the Service may include: automated answering of inbound calls; caller intake and urgency triage; automated follow-up messaging; escalation notifications; call recording and transcription; a lead dashboard; appointment booking; and outbound SMS campaigns. Features vary by plan, and the plan selected at signup governs what is included.'],
  ['2. Client Responsibilities', 'Client agrees to: (a) provide accurate and current business information during onboarding, including services offered, hours, service area, urgency definitions, and escalation contacts; (b) complete any carrier-side call forwarding required to route calls to the Service; (c) keep escalation contact details current; and (d) notify CallerCore of material changes to the business that would affect how calls should be handled. The Service\'s accuracy depends on the information Client provides.'],
  ['3. Acceptable Use', 'Client will not use the Service to: transmit unlawful, harassing, fraudulent, or deceptive content; impersonate another business or individual; violate any applicable telecommunications, consumer protection, or privacy law; or resell or provide the Service to third parties without CallerCore\'s written consent. CallerCore may suspend the Service, with notice where practicable, if it reasonably believes it is being used in violation of this Section.'],
  ['4. Fees & Payment', '4.1 Setup fee. A one-time setup fee of $500 is due at signup, non-refundable, as it covers configuration and build labor already performed.\n4.2 Monthly subscription. Client is billed monthly in advance according to the selected plan.\n4.3 Recurring billing authorization. Client authorizes CallerCore to charge the payment method on file, on a recurring basis, for the monthly subscription fee and any applicable overage or fees, until this Agreement is cancelled under Section 6. Client is responsible for keeping payment details current.\n4.4 Overage. Minutes beyond the plan\'s included minutes are billed at $0.30 per minute in arrears.\n4.5 Failed or late payment. If a payment fails, CallerCore may retry the payment method and will notify Client. If payment remains outstanding after fourteen (14) days, CallerCore may suspend the Service until the balance is cleared. Suspension does not delete Client data.\n4.6 Price changes. CallerCore may change subscription pricing with at least thirty (30) days\' written notice. Changes take effect at the start of the next billing period, and Client may cancel under Section 6 before the new pricing applies.\n4.7 Taxes. Fees are exclusive of any applicable sales, use, or telecommunications taxes, which are Client\'s responsibility.\n4.8 No long-term contract. This Agreement has no minimum term. Either party may cancel per Section 6.'],
  ['5. Guarantee', 'If Client is not satisfied within thirty (30) days of go-live, CallerCore will refund the monthly subscription fee for that period in full upon request. The setup fee is non-refundable.'],
  ['6. Term & Cancellation', 'This Agreement continues month-to-month. Either party may cancel at any time with written notice (email is sufficient); cancellation is effective at the end of the then-current billing period. Fees already paid for the current period are not prorated except as provided in Section 5. CallerCore may suspend or terminate the Service for non-payment or for breach of Sections 3, 12, or 13, with notice where practicable.'],
  ['7. Service Availability & Third-Party Dependencies', 'The Service depends on third-party providers including telephony carriers, voice and language model providers, and CRM platforms. CallerCore does not guarantee uninterrupted or error-free operation and does not offer a contractual uptime commitment. CallerCore is not liable for interruptions, degradation, or failures caused by third-party providers, carrier outages, or events outside its reasonable control, but will use commercially reasonable efforts to restore the Service promptly and to notify Client of material disruptions.'],
  ['8. Warranty Disclaimer', 'EXCEPT AS EXPRESSLY STATED IN THIS AGREEMENT, THE SERVICE IS PROVIDED "AS IS" AND "AS AVAILABLE." CALLERCORE DISCLAIMS ALL OTHER WARRANTIES, EXPRESS OR IMPLIED, INCLUDING ANY IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE, AND NON-INFRINGEMENT. CallerCore does not warrant that the Service will capture every lead, correctly classify every call, or produce any particular business result.'],
  ['9. Service Limitations & Liability', 'The Service is automated and, like any phone or software system, may occasionally misroute, misinterpret, or fail to fully resolve an individual call. CallerCore\'s total aggregate liability for any claim arising out of or relating to this Agreement or the Service is limited to the fees Client paid to CallerCore in the three (3) months preceding the event giving rise to the claim. CallerCore is not liable for indirect, incidental, consequential, special, punitive, or lost-profit damages, or for lost business opportunities, even if advised of the possibility. All calls are recorded and reviewed; identified issues are corrected and, where appropriate, escalated to Client the same business day. The Service is not a substitute for emergency services, and callers reporting life-safety emergencies are directed to contact 911 or the appropriate utility.'],
  ['10. Indemnification', 'Client will defend, indemnify, and hold harmless CallerCore and its officers, employees, and contractors from any third-party claim, demand, penalty, or proceeding, including reasonable attorneys\' fees, arising out of: (a) Client\'s breach of Sections 3, 12, or 13; (b) content, contact lists, or instructions Client provides; (c) Client\'s violation of any applicable law, including the Telephone Consumer Protection Act or state recording-consent laws; or (d) Client\'s business operations or the services Client delivers to its own customers. CallerCore will promptly notify Client of any such claim and may participate in its defense with counsel of its own choosing at its own expense.'],
  ['11. Call Recording & Consent', 'All calls handled by the Service are recorded and transcribed for quality assurance and lead-capture purposes. Client\'s AI agent greeting includes a recording disclosure to callers consistent with applicable law, including Washington\'s all-party consent requirement where applicable. Client authorizes CallerCore to record calls placed to Client\'s business line on Client\'s behalf, and is responsible for ensuring that recording practices comply with the laws of the jurisdictions in which Client and its callers are located.'],
  ['12. Messaging, Consent & Compliance', 'Where Client\'s plan includes SMS features, Client is responsible for ensuring it has a lawful basis to message the recipients it provides, and agrees not to use the Service to send unsolicited messages to purchased, scraped, or otherwise non-consented lists. Automated follow-up messages to individuals who have just contacted Client\'s business are sent on Client\'s behalf. Client agrees to comply with the Telephone Consumer Protection Act and applicable messaging regulations, and CallerCore may suspend messaging features if it reasonably believes they are being used in violation of those rules. Opt-out handling is enabled by default and may not be disabled.'],
  ['13. Regulated & Sensitive Data', 'The Service is not designed for, and is not certified as compliant with, HIPAA, PCI-DSS, GLBA, or similar regulatory frameworks. Client must not use the Service to collect, transmit, or store protected health information, payment card data, financial account numbers, government identification numbers, or other regulated sensitive data, and must configure its AI agent so that callers are not prompted to provide such information. Client is solely responsible for any regulated data it causes to enter the Service. If Client operates in a regulated industry and requires a compliant configuration, it must contact CallerCore in writing before go-live so that a separate arrangement, including any required business associate agreement, can be evaluated.'],
  ['14. Client Data & Ownership', 'All call transcripts, lead data, and business configuration information collected through the Service belong to Client. CallerCore processes this data solely to provide and improve the Service for Client, and will not sell it. CallerCore may use aggregated, de-identified usage data that does not identify Client or any caller to operate and improve the Service. Upon cancellation, CallerCore will export and provide Client\'s contact and lead data upon request, and will retain data thereafter only as long as reasonably necessary or as required by law.'],
  ['15. Intellectual Property', 'CallerCore retains all right, title, and interest in the Service, including its software, prompt engineering, agent templates, configurations, workflows, and documentation, together with any improvements to them. Nothing in this Agreement transfers ownership of the Service to Client. Client is granted a non-exclusive, non-transferable right to use the Service during the term. Client retains all rights to its own business name, marks, content, and data, and grants CallerCore a limited licence to use them solely to provide the Service.'],
  ['16. Confidentiality', 'Each party agrees to keep confidential any non-public business information disclosed by the other party in connection with this Agreement, to use it only for purposes of this Agreement, and to protect it with at least reasonable care. This obligation does not apply to information that is publicly available, independently developed, or lawfully obtained from a third party, or where disclosure is required by law.'],
  ['17. Independent Contractor', 'CallerCore provides the Service as an independent contractor, not as an employee, partner, agent, or joint venturer of Client, except to the limited extent it acts on Client\'s behalf in answering calls and sending messages as configured by Client.'],
  ['18. Force Majeure', 'Neither party is liable for any failure or delay in performance caused by events beyond its reasonable control, including natural disasters, war, terrorism, labor disputes, government action, widespread internet or telecommunications failure, or third-party provider outages. This does not excuse Client\'s obligation to pay fees for Services already provided.'],
  ['19. Assignment', 'Neither party may assign this Agreement without the other party\'s written consent, except that either party may assign it in connection with a merger, acquisition, or sale of substantially all of its assets, with notice to the other party.'],
  ['20. Notices', 'Notices under this Agreement may be given by email to the addresses the parties have on file - for CallerCore, support@callercore.com, and for Client, the contact email provided during onboarding. Notice is deemed received on the next business day after sending, provided no delivery failure is received. Each party is responsible for keeping its contact email current.'],
  ['21. Governing Law & Venue', 'This Agreement is governed by the laws of the State of Washington, without regard to conflict-of-laws principles. The parties submit to the exclusive jurisdiction of the state and federal courts located in Spokane County, Washington, and each party waives any objection to venue in those courts.'],
  ['22. Severability & Survival', 'If any provision of this Agreement is held unenforceable, that provision will be limited or severed to the minimum extent necessary and the remainder will remain in full force. Sections 8, 9, 10, 13, 14, 15, 16, 21, and 22 survive termination of this Agreement.'],
  ['23. Entire Agreement & Modifications', 'This Agreement, together with the plan details confirmed at signup, constitutes the entire agreement between the parties regarding the Service and supersedes any prior discussions or representations. Any modification must be in writing and agreed by both parties. A failure to enforce any provision is not a waiver of the right to enforce it later.'],
];

module.exports = { CLAUSES };
