const test=require('node:test'),assert=require('node:assert/strict');
const {billingEmailRecord,enqueueBillingEmail,deliverBillingEmail}=require('../lib/billing-email-outbox');
const event={operationId:'evt_test_invoice',workspaceId:'fixture',to:'preview@example.test',type:'invoice',plan:'Starter',amount:34900};
function storage(){const records=new Map();return {records,get:async k=>structuredClone(records.get(k)??null),eval:async(_,keys,args)=>{for(let i=0;i<keys.length;i++)if((records.has(keys[i])?JSON.stringify(records.get(keys[i])):'')!==args[i*2])return 0;keys.forEach((key,i)=>records.set(key,JSON.parse(args[i*2+1])));return 1}}}
test('billing emails link directly to CallerCore Billing and safely summarize payment',()=>{const mail=billingEmailRecord({...event,payment:{brand:'Visa',last4:'4242',cvc:'sensitive'}});assert.match(mail.html,/dashboard\?view=billing/);assert.match(mail.text,/349/);assert.doesNotMatch(mail.html,/sensitive|billing\.stripe\.com/)});
test('one billing event is queued once across replays',async()=>{const kv=storage(),a=await enqueueBillingEmail(kv,event),b=await enqueueBillingEmail(kv,event);assert.equal(a.key,b.key);assert.equal(kv.records.size,1)});
test('Preview captures branded messages without transmitting any mail',async()=>{const kv=storage(),{key}=await enqueueBillingEmail(kv,event);const result=await deliverBillingEmail(kv,key,()=>{throw Error('must not send')},{VERCEL_ENV:'preview'});assert.equal(result.status,'captured')});
test('live email delivery remains closed until settings duplication review is accepted',async()=>{const kv=storage(),{key}=await enqueueBillingEmail(kv,event);assert.equal((await deliverBillingEmail(kv,key,()=>{throw Error('must not send')},{})).status,'queued')});
test('verified receipt prevents duplicate sends',async()=>{const kv=storage(),{key}=await enqueueBillingEmail(kv,event);let sends=0;const send=async()=>{sends++;return {id:'mailgun-receipt'}};const env={CALLERCORE_BILLING_EMAILS_ENABLED:'true'};assert.equal((await deliverBillingEmail(kv,key,send,env)).status,'sent');await deliverBillingEmail(kv,key,send,env);assert.equal(sends,1)});
test('ambiguous provider response is held for review instead of resent',async()=>{const kv=storage(),{key}=await enqueueBillingEmail(kv,event);let sends=0;const send=async()=>{sends++;throw Error('timeout')},env={CALLERCORE_BILLING_EMAILS_ENABLED:'true'};assert.equal((await deliverBillingEmail(kv,key,send,env)).status,'uncertain');await deliverBillingEmail(kv,key,send,env);assert.equal(sends,1)});
test('concurrent delivery claims cannot send twice',async()=>{const kv=storage(),{key}=await enqueueBillingEmail(kv,event);let sends=0;await Promise.allSettled([deliverBillingEmail(kv,key,async()=>{sends++;return {id:'receipt'}},{CALLERCORE_BILLING_EMAILS_ENABLED:'true'}),deliverBillingEmail(kv,key,async()=>{sends++;return {id:'receipt'}},{CALLERCORE_BILLING_EMAILS_ENABLED:'true'})]);assert.equal(sends,1)});
