const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const {presentation}=require('../checkout-confirmation');
test('paid purchase is presented as complete even before workspace fulfillment',()=>{
 const p=presentation({paid:true,onboarding:false});assert.equal(p.paid,true);assert.ok(!p.checkout);assert.ok(!p.account);assert.match(p.title,/confirmed/);assert.match(p.message,/purchase is complete/);
});
test('account access is offered only after persisted fulfillment',()=>{assert.equal(presentation({paid:true,onboarding:true}).account,true);assert.ok(!presentation({paid:false,onboarding:true,status:'complete'}).account);});
test('provider processing is not represented as a failure or an opportunity to pay twice',()=>{const p=presentation({paid:false,onboarding:false,status:'complete'});assert.equal(p.state,'processing');assert.ok(!p.checkout);assert.ok(!p.paid);});
test('expired and unsubmitted sessions have explicit checkout recovery',()=>{for(const status of ['expired','open']){const p=presentation({paid:false,onboarding:false,status});assert.equal(p.checkout,true);assert.equal(p.terminal,true);assert.ok(!p.paid);}});
test('a delayed response never regresses a payment already confirmed',()=>{const p=presentation({paid:false,onboarding:false,status:'open'},true);assert.equal(p.state,'paid');assert.equal(p.paid,true);assert.ok(!p.checkout);});
test('unknown statuses cannot fabricate payment success or permit another purchase',()=>{assert.throws(()=>presentation({paid:false,onboarding:false,status:'unknown'}));});
function browser(responses,receipt='a'.repeat(48)){
 const nodes=new Map(),listeners=new Map(),timers=[],removed=[];const node=id=>{if(!nodes.has(id))nodes.set(id,{hidden:true,disabled:false,dataset:{},textContent:'',classList:{toggle(){}},addEventListener(type,fn){listeners.set(id+':'+type,fn);}});return nodes.get(id);};
 const scope={document:{getElementById:node,querySelector:()=>node('card')},location:{search:'?receipt='+receipt},URLSearchParams,AbortController,Intl,Date,sessionStorage:{removeItem:k=>removed.push(k)},setTimeout:fn=>{timers.push(fn);return timers.length;},clearTimeout(){},fetch:async()=>{const r=responses.shift();if(r instanceof Error)throw r;return {ok:r.ok!==false,status:r.httpStatus||200,json:async()=>r};},addEventListener(){}};scope.window=scope;vm.runInNewContext(fs.readFileSync('checkout-confirmation.js','utf8'),scope);return {node,listeners,timers,removed,settle:()=>new Promise(r=>setImmediate(r))};
}
test('connection failure after confirmed payment retains the receipt and enables status checking',async()=>{
 const b=browser([{paid:true,onboarding:false,plan:'Starter',amountTotal:84900,currency:'usd'},Error('offline')]);await b.settle();assert.equal(b.node('card').dataset.state,'paid');assert.match(b.node('receiptAmount').textContent,/849/);await b.listeners.get('checkConfirmation:click')();await b.settle();assert.equal(b.node('card').dataset.state,'paid');assert.equal(b.node('checkoutLink').hidden,true);assert.equal(b.node('checkConfirmation').disabled,false);assert.match(b.node('checkNote').textContent,/confirmed/);
});
test('unavailable confirmation offers a status check and support without claiming payment failed',async()=>{const b=browser([Error('offline')]);await b.settle();assert.equal(b.node('card').dataset.state,'unavailable');assert.equal(b.node('checkoutLink').hidden,true);assert.equal(b.node('accountLink').hidden,true);assert.equal(b.node('checkConfirmation').disabled,false);assert.match(b.node('returnStatus').textContent,/doesn’t tell us/);});
test('invalid private link makes no provider request and gives support guidance',async()=>{const b=browser([], 'invalid');await b.settle();assert.equal(b.node('card').dataset.state,'link');assert.equal(b.node('checkConfirmation').hidden,true);assert.match(b.node('confirmationDetail').textContent,/team/);});
test('different-browser receipt access explains privacy without claiming a failed payment',async()=>{const b=browser([{ok:false,httpStatus:403}]);await b.settle();assert.equal(b.node('card').dataset.state,'link');assert.equal(b.node('checkoutLink').hidden,true);assert.equal(b.node('checkConfirmation').hidden,true);assert.match(b.node('returnStatus').textContent,/browser where/);});
test('a confirmed fulfilled account clears the old attempt and reveals account access',async()=>{const b=browser([{paid:true,onboarding:true,plan:'Growth',amountTotal:109900,currency:'usd'}]);await b.settle();assert.equal(b.node('accountLink').hidden,false);assert.deepEqual(b.removed,['cc_checkout_attempt','cc_checkout_draft']);assert.equal(b.node('checkConfirmation').hidden,true);});
test('only an explicitly reopened expired checkout clears its old attempt',async()=>{const b=browser([{paid:false,onboarding:false,status:'expired'}]);await b.settle();assert.deepEqual(b.removed,[]);b.listeners.get('checkoutLink:click')();assert.deepEqual(b.removed,['cc_checkout_attempt','cc_checkout_draft']);});
