const test=require('node:test'),assert=require('node:assert/strict');
const {beginCheckout,checkoutStatus}=require('../lib/native-checkout');
const {verifiedPurchase}=require('../lib/checkout-payment-proof');
const {providerConfig}=require('../lib/billing-provider');
function fixture(){
  const env={VERCEL_ENV:'preview',CALLERCORE_CHECKOUT_ENABLED:'true',STRIPE_SECRET_KEY:'sk_test_fixture',STRIPE_PUBLISHABLE_KEY:'pk_test_fixture',STRIPE_PRICE_STARTER:'price_starter',STRIPE_PRICE_GROWTH:'price_growth',STRIPE_PRICE_PRO:'price_pro',STRIPE_PRICE_SETUP:'price_setup'},records=new Map(),locks=new Map(),providerKeys=new Map(),calls=[];let creates=0,failAfterCreate=false;
  const kv={get:async key=>structuredClone(records.get(key)??null),eval:async(script,keys,args)=>{if(script.includes("'EX',ARGV[2]")){if(locks.has(keys[0]))return 0;locks.set(keys[0],args[0]);return 1}if(script.includes("~=ARGV[1]")){if(locks.get(keys[0])!==args[0])return 0;locks.delete(keys[0]);return 1}for(let i=0;i<keys.length;i++)if((records.has(keys[i])?JSON.stringify(records.get(keys[i])):'')!==args[i*2])return 0;keys.forEach((key,i)=>records.set(key,JSON.parse(args[i*2+1])));return 1}};
  const provider={config:providerConfig(env),request:async(path,options={})=>{calls.push({path,options});if(path.startsWith('/prices/'))return {id:path.split('/').at(-1),active:true,currency:'usd',unit_amount:path.endsWith('setup')?50000:34900,recurring:path.endsWith('setup')?null:{interval:'month',usage_type:'licensed'}};if(path==='/checkout/sessions'){if(!providerKeys.has(options.idempotencyKey)){creates++;providerKeys.set(options.idempotencyKey,{id:'cs_test_native',client_secret:'cs_test_native_secret_fixture',mode:'subscription',status:'open',payment_status:'unpaid',client_reference_id:options.params.client_reference_id,customer_email:options.params.customer_email,metadata:{plan:'Starter',attempt_hash:options.params['metadata[attempt_hash]']}})}if(failAfterCreate){failAfterCreate=false;throw Error('network after provider created session')}return structuredClone(providerKeys.get(options.idempotencyKey))}if(path==='/checkout/sessions/cs_test_native')return structuredClone([...providerKeys.values()][0]);throw Error('Unexpected '+path)}};
  const req={headers:{},body:{native:true,attemptId:'a'.repeat(48),billingTermsAccepted:true,plan:'Starter',name:'Client',business:'Business',email:'client@example.test',phone:'+15095551212',industry:'Home Services'}},headers={};
  const begin=()=>beginCheckout({kv,req,res:{setHeader:(k,v)=>headers[k]=v},origin:'https://preview.example.test',env,provider,upsertWebsiteProspect:async()=>({id:'prospect_fixture',email:req.body.email})});
  return {env,records,providerKeys,kv,provider,req,headers,calls,begin,get creates(){return creates},failNext(){failAfterCreate=true}};
}
test('public checkout launch gate refuses all provider calls',async()=>{const f=fixture();f.env.CALLERCORE_CHECKOUT_ENABLED='false';await assert.rejects(f.begin(),/not open/);assert.equal(f.calls.length,0)});
test('billing terms are required before a signup payment can be prepared',async()=>{const f=fixture();f.req.body.billingTermsAccepted=false;await assert.rejects(f.begin(),/billing terms/);assert.equal(f.creates,0)});
test('native signup prepares exactly monthly plan plus setup, tax and overages remain disabled',async()=>{const f=fixture(),r=await f.begin();assert.equal(r.summary.dueToday,84900);assert.equal(r.summary.overageEnabled,false);const params=f.calls.find(c=>c.path==='/checkout/sessions').options.params;assert.equal(params.ui_mode,'elements');assert.equal(params['automatic_tax[enabled]'],false);assert.equal(params['line_items[1][price]'],'price_setup');assert.equal(Object.keys(params).filter(k=>k.includes('[price]')).length,2);assert.match(f.headers['Set-Cookie'],/HttpOnly; Secure; SameSite=Lax/)});
test('refresh and duplicate submit reuse one durable checkout session',async()=>{const f=fixture(),a=await f.begin(),b=await f.begin();assert.equal(a.clientSecret,b.clientSecret);assert.equal(f.creates,1)});
test('ambiguous session creation retries identical provider idempotency key without duplicate purchase',async()=>{const f=fixture();f.failNext();await assert.rejects(f.begin(),/network/);const r=await f.begin();assert.ok(r.clientSecret);assert.equal(f.creates,1)});
test('changed business or plan does not silently reuse a stale price confirmation',async()=>{const f=fixture();await f.begin();f.req.body.plan='Growth';await assert.rejects(f.begin(),/details changed/);assert.equal(f.creates,1)});
test('a second browser checkout for the same email is blocked while the original is open',async()=>{const f=fixture();await f.begin();f.req.body.attemptId='b'.repeat(48);await assert.rejects(f.begin(),/already open/);assert.equal(f.creates,1)});
test('receipt cannot leak signup details to a browser without its HttpOnly binding',async()=>{const f=fixture(),r=await f.begin();await assert.rejects(checkoutStatus({kv:f.kv,provider:f.provider,req:{query:{receipt:r.receipt},headers:{cookie:'cc_checkout_receipt='+'b'.repeat(48)}}}),/browser/)});
test('payment before webhook is confirmed but onboarding remains pending until durable fulfillment',async()=>{const f=fixture(),r=await f.begin(),session=[...f.providerKeys.values()][0];session.status='complete';session.payment_status='paid';const req={query:{receipt:r.receipt},headers:{cookie:'cc_checkout_receipt='+r.receipt}};const before=await checkoutStatus({kv:f.kv,provider:f.provider,req});assert.equal(before.paid,true);assert.equal(before.onboarding,false);assert.equal(before.reconciliationPending,true);f.records.set('stripe:session:cs_test_native',{workspaceId:'w',status:'awaiting_review'});assert.equal((await checkoutStatus({kv:f.kv,provider:f.provider,req})).onboarding,true)});
function paidProvider(){const config=providerConfig({VERCEL_ENV:'preview',STRIPE_SECRET_KEY:'sk_test_fixture',STRIPE_PRICE_STARTER:'price_starter',STRIPE_PRICE_GROWTH:'price_growth',STRIPE_PRICE_PRO:'price_pro'}),session={id:'cs_test_native',mode:'subscription',status:'complete',payment_status:'paid',customer:'cus_fixture',subscription:'sub_fixture',metadata:{plan:'Starter'},automatic_tax:{enabled:false}},lines={data:[{quantity:1,price:{id:'price_starter',unit_amount:34900,currency:'usd',recurring:{interval:'month',usage_type:'licensed'}}},{quantity:1,price:{id:'price_setup',unit_amount:50000,currency:'usd'}}]},subscription={id:'sub_fixture',customer:'cus_fixture',status:'active',items:{data:[{price:{id:'price_starter'},current_period_end:1900000000}]}};return {session,lines,subscription,provider:{config,request:async path=>path.endsWith('line_items')?lines:path.startsWith('/subscriptions/')?subscription:session}}}
test('paid order is verified from canonical session, exact line items and subscription',async()=>{const f=paidProvider(),result=await verifiedPurchase(f.session,f.provider,{STRIPE_PRICE_SETUP:'price_setup'});assert.equal(result._verifiedPlan,'Starter');assert.equal(result._billing.status,'active')});
for(const failure of ['unpaid','overage','tax','setup','wrongCustomer','wrongPlan'])test('paid onboarding rejects '+failure,async()=>{const f=paidProvider();if(failure==='unpaid')f.session.payment_status='unpaid';if(failure==='overage')f.lines.data.push({quantity:1,price:{id:'price_overage'}});if(failure==='tax')f.session.automatic_tax.enabled=true;if(failure==='setup')f.lines.data[1].price.unit_amount=0;if(failure==='wrongCustomer')f.subscription.customer='cus_other';if(failure==='wrongPlan')f.session.metadata.plan='Pro';await assert.rejects(verifiedPurchase(f.session,f.provider,{STRIPE_PRICE_SETUP:'price_setup'}))});
