const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');const root=path.join(__dirname,'..');const read=f=>fs.readFileSync(path.join(root,f),'utf8');
test('homepage navigation has a single owner rather than competing click toggles',()=>{assert.doesNotMatch(read('index.html'),/menu\.addEventListener/);assert.match(read('index.html'),/src="\/site.js"/)});
test('illustrative homepage calls are not represented as live activity',()=>{const s=read('index.html');assert.match(s,/Example call/);assert.match(s,/INTERACTIVE EXAMPLE/);assert.doesNotMatch(s,/CALLERCORE LIVE|id="demoTimer"|class="live-pill">LIVE/);assert.match(s,/Payment starts setup/)});
test('public navigation closes on Escape and viewport changes with truthful accessible state',()=>{const src=read('site.js');const begin=src.indexOf('  if(menu && nav){'),end=src.indexOf("\n  document.querySelectorAll('a[href",begin);const events={},classes=new Set(),attrs={};const nav={id:'primary-nav',querySelector:()=>({focus:()=>attrs.firstLinkFocused=true}),classList:{contains:x=>classes.has(x),toggle:(x,v)=>v?classes.add(x):classes.delete(x)},addEventListener:(k,f)=>events['nav:'+k]=f};const menu={setAttribute:(k,v)=>attrs[k]=v,addEventListener:(k,f)=>events['menu:'+k]=f,focus:()=>attrs.focus=true};const doc={body:{classList:{toggle:()=>{}}},addEventListener:(k,f)=>events['doc:'+k]=f};const context={menu,nav,header:{contains:()=>false},document:doc,window:{matchMedia:()=>({addEventListener:(k,f)=>events.resize=f})}};vm.runInNewContext(src.slice(begin,end),context);events['menu:click']();assert.equal(attrs['aria-expanded'],'true');assert.equal(attrs['aria-label'],'Close navigation');assert.equal(attrs.firstLinkFocused,true);events['doc:keydown']({key:'Escape'});assert.equal(attrs['aria-expanded'],'false');assert.equal(attrs.focus,true);events['menu:click']();events.resize();assert.equal(classes.has('open'),false);assert.equal(attrs['aria-label'],'Open navigation')});
test('public visual system is opt-in and preserves checkout/contact identifiers',()=>{for(const f of ['index.html','contact.html','live-demo.html','get-started.html','privacy.html','terms.html']){const s=read(f);assert.match(s,/class="public-site/);assert.match(s,/href="\/public-premium.css"/)}assert.match(read('contact.html'),/id="contactForm"/);assert.match(read('get-started.html'),/id="embeddedCheckout"/);assert.match(read('live-demo.html'),/id="demoBtn"/)});
test('phone navigation contains keyboard focus and backdrop dismissal restores its trigger',()=>{
 const src=read('site.js'),begin=src.indexOf('  if(menu && nav){'),end=src.indexOf("\n  document.querySelectorAll('a[href",begin),events={},classes=new Set();
 const doc={body:{classList:{toggle:()=>{}}},addEventListener:(k,f)=>events[k]=f};
 const first={focus:()=>doc.activeElement=first},last={focus:()=>doc.activeElement=last};
 const backdrop={hidden:true,addEventListener:(k,f)=>events.backdrop=f};doc.querySelector=()=>backdrop;
 const menu={setAttribute:()=>{},addEventListener:(k,f)=>events.menu=f,focus:()=>doc.activeElement=menu};
 const nav={id:'primary-nav',querySelector:()=>first,querySelectorAll:()=>[first,last],classList:{contains:k=>classes.has(k),toggle:(k,v)=>v?classes.add(k):classes.delete(k)},addEventListener:()=>{}};
 vm.runInNewContext(src.slice(begin,end),{menu,nav,document:doc,header:{contains:()=>true},window:{matchMedia:()=>({addEventListener:()=>{}})}});
 events.menu();assert.equal(backdrop.hidden,false);assert.equal(doc.activeElement,first);
 let prevented=0;const tab=shiftKey=>events.keydown({key:'Tab',shiftKey,preventDefault:()=>prevented++});
 tab(true);assert.equal(doc.activeElement,menu);tab(true);assert.equal(doc.activeElement,last);tab(false);assert.equal(doc.activeElement,menu);tab(false);assert.equal(doc.activeElement,first);assert.equal(prevented,4);
 events.backdrop();assert.equal(backdrop.hidden,true);assert.equal(classes.has('open'),false);assert.equal(doc.activeElement,menu);
});
test('checkout step changes move focus to the active heading and respect reduced motion',()=>{const source=read('get-started.html');const fn=source.slice(source.indexOf('function showStage(n){'),source.indexOf('function choose(p){'));const focused=[],attrs={},states=[];const heading={setAttribute:(k,v)=>attrs[k]=v,focus:options=>focused.push(options)};const stage={classList:{toggle:(k,v)=>states.push([k,v])},querySelector:()=>heading};const scroll=[];vm.runInNewContext(fn+'showStage(2)',{stages:[null,stage,stage,stage],progress:[null,stage,stage,stage],document:{querySelector:()=>({offsetTop:240})},window:{matchMedia:()=>({matches:true}),scrollTo:x=>scroll.push(x)}});assert.equal(attrs.tabindex,'-1');assert.equal(focused.length,1);assert.equal(focused[0].preventScroll,true);assert.equal(scroll[0].behavior,'instant');assert.equal(scroll[0].top,140);assert.ok(states.some(([k,v])=>k==='active'&&v===true))});
