const test=require('node:test');
const assert=require('node:assert/strict');
const {estimateMinutes,createPlayback,scenarios}=require('../public-experience');
function fixture(){const callbacks=[],cancelled=[],states=[];const playback=createPlayback({count:4,onChange:s=>states.push(s),schedule:fn=>{callbacks.push(fn);return callbacks.length},cancel:id=>cancelled.push(id)});return {playback,callbacks,cancelled,states,last:()=>states.at(-1)}}
test('call volume estimates remain finite at plan boundaries and reject malformed input',()=>{assert.equal(estimateMinutes(20,3),260);assert.equal(estimateMinutes(45,3),585);assert.equal(estimateMinutes(50,3),650);assert.equal(estimateMinutes(100,8),3464);assert.equal(estimateMinutes('bad',3),null);assert.equal(estimateMinutes(Infinity,3),null);assert.equal(estimateMinutes(-10,50),173)});
test('switching scenarios invalidates an already queued playback callback',()=>{const f=fixture();f.playback.toggle();const stale=f.callbacks[0];f.playback.reset();stale();assert.deepEqual(f.last(),{step:0,playing:false});assert.equal(f.states.length,2);assert.deepEqual(f.cancelled,[1])});
test('manual next pauses playback and a stale timer cannot skip a conversation moment',()=>{const f=fixture();f.playback.toggle();f.playback.next();f.callbacks[0]();assert.deepEqual(f.last(),{step:1,playing:false});f.playback.next();f.playback.next();f.playback.next();assert.deepEqual(f.last(),{step:0,playing:false})});
test('playback finishes once, replay restarts, and pause preserves the current moment',()=>{const f=fixture();f.playback.toggle();f.callbacks[0]();f.callbacks[1]();f.callbacks[2]();assert.deepEqual(f.last(),{step:3,playing:false});assert.equal(f.callbacks.length,3);f.playback.toggle();assert.deepEqual(f.last(),{step:0,playing:true});f.playback.pause();f.callbacks[3]();assert.deepEqual(f.last(),{step:0,playing:false})});
test('every example includes four complete exchanges and distinguishes requests from confirmed appointments',()=>{for(const s of Object.values(scenarios)){assert.equal(s.moments.length,4);for(const m of s.moments){assert.equal(m.length,3);assert.ok(m.every(x=>typeof x==='string'&&x.length>5))}}assert.match(scenarios.booking.moments[3][1],/confirm a time/);assert.match(scenarios.booking.moments[3][2],/requested/)});
test('ambient playback loops at configured pace and pause invalidates the pending loop',()=>{const queue=[],states=[],delays=[];const p=createPlayback({count:4,loop:true,interval:4600,onChange:s=>states.push(s),schedule:(fn,ms)=>{queue.push(fn);delays.push(ms);return queue.length},cancel:()=>{}});p.toggle();for(let i=0;i<4;i++)queue[i]();assert.deepEqual(states.at(-1),{step:0,playing:true});assert.ok(delays.every(ms=>ms===4600));p.pause();queue[4]();assert.deepEqual(states.at(-1),{step:0,playing:false})});
