const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const html=fs.readFileSync('get-started.html','utf8'),start=html.indexOf("document.getElementById('confirmSignupPayment').addEventListener('click',async()=>{");
const source=html.slice(start,html.indexOf('</script>',start));
function browser(confirm){let handler;const nodes=new Map(),nav=[];const node=id=>{if(!nodes.has(id))nodes.set(id,{checked:true,disabled:false,hidden:true,textContent:'',children:[],focus(){},appendChild(el){this.children.push(el)},addEventListener(type,fn){handler=fn}});return nodes.get(id)};
 const context={paymentProcessing:false,checkoutActions:{confirm},checkoutReceipt:'a'.repeat(48),document:{getElementById:node,createElement:()=>({})},location:{assign:url=>nav.push(url)},encodeURIComponent};vm.runInNewContext(source,context);return {run:()=>handler(),node,nav};}
test('a bank decline explains the reason and restores payment correction controls',async()=>{const b=browser(async()=>({error:{type:'card_error',message:'Your card has insufficient funds.'}}));await b.run();assert.match(b.node('paymentError').textContent,/insufficient funds/);assert.equal(b.node('confirmSignupPayment').disabled,false);assert.equal(b.node('backToBusiness').disabled,false);assert.equal(b.nav.length,0);});
test('a network interruption offers the same private confirmation instead of another payment',async()=>{const b=browser(async()=>{throw Error('Failed to fetch')});await b.run();assert.equal(b.node('confirmSignupPayment').disabled,true);assert.equal(b.node('backToBusiness').disabled,true);const link=b.node('paymentError').children[0];assert.equal(link.href,'/checkout-complete?receipt='+'a'.repeat(48));assert.match(link.textContent,/Check payment status/);assert.doesNotMatch(b.node('paymentError').textContent,/payment failed/i);});
test('a provider connection error with a generic message also requires status verification',async()=>{const b=browser(async()=>({error:{type:'api_connection_error',message:'Something went wrong.'}}));await b.run();assert.equal(b.node('confirmSignupPayment').disabled,true);assert.equal(b.node('paymentError').children.length,1);});
test('a successful payment still opens the private receipt and never shows a failure',async()=>{const b=browser(async()=>({}));await b.run();assert.equal(b.nav[0],'/checkout-complete?receipt='+'a'.repeat(48));assert.equal(b.node('paymentError').hidden,true);});
function resume({receipt='a'.repeat(48),attempt='a'.repeat(48),draft={attemptId:'a'.repeat(48),plan:'Growth',business:'Example Company',email:'owner@example.test',billingTermsAccepted:true}}={}){
 const values={},stages=[],plans=[],draftSource=html.slice(html.indexOf('// Restore business details'),html.indexOf('</script>',html.indexOf('// Restore business details')));
 vm.runInNewContext(draftSource,{URLSearchParams,location:{search:'?resume='+receipt},PLAN:{Starter:{},Growth:{},Pro:{}},sessionStorage:{getItem:key=>key==='cc_checkout_draft'?JSON.stringify(draft):attempt},choose:value=>plans.push(value),showStage:value=>stages.push(value),document:{getElementById:()=>({elements:{namedItem:key=>values[key]||=( {})}})}});return {values,stages,plans};
}
test('continuing a verified open checkout restores its original business details without submitting payment',()=>{const b=resume();assert.deepEqual(b.plans,['Growth']);assert.deepEqual(b.stages,[2]);assert.equal(b.values.business.value,'Example Company');assert.equal(b.values.email.value,'owner@example.test');assert.equal(b.values.billingTermsAccepted.checked,true);});
test('a resume URL cannot restore another attempt or a stale draft',()=>{for(const input of [{receipt:'b'.repeat(48)},{attempt:'b'.repeat(48)},{draft:null}]){const b=resume(input);assert.equal(b.stages.length,0);assert.equal(Object.keys(b.values).length,0);}});
