const test=require('node:test'),assert=require('node:assert/strict'),{reconcile}=require('../lib/voice-reconcile');
function fixture(){const values={'workspace:test':{voiceTestWorkspace:true},'voice:pending:test':{}};for(let i=0;i<12;i++){values['voice:pending:test']['call_'+i]=true;values['voice:call:call_'+i]={workspaceId:'test',providerCallId:'provider_'+i}}return {values,get:async key=>structuredClone(values[key]??null),set:async(key,value,opts)=>{if(opts?.nx&&values[key])return null;values[key]=value;return 'OK'},eval:async(script,keys,args)=>{if(script===require('../lib/voice-reconcile').RELEASE){if(values[keys[0]]===args[0]){delete values[keys[0]];return 1}return 0}const n=Number(args[0]);for(let i=0;i<n;i++)if((values[keys[i]]==null?'':JSON.stringify(values[keys[i]]))!==args[2*i+1])return 0;for(let i=0;i<n;i++)values[keys[i]]=JSON.parse(args[2*i+2]);values[keys[n]]=[JSON.parse(args[n*2+1]),...(values[keys[n]]||[])];return 1}}}
test('reconciliation bounds a large queue and preserves remaining work',async()=>{const kv=fixture(),seen=[];const result=await reconcile(kv,'test',{process:async(_,event)=>{seen.push(event.call.id);delete kv.values['voice:pending:test']['call_'+(seen.length-1)]}});assert.equal(result.checked,5);assert.equal(seen.length,5);assert.equal(result.failed,0);assert.equal(result.pending,7)});
test('slow provider stops the batch at its deadline without erasing pending records',async()=>{const kv=fixture();let clock=0;const result=await reconcile(kv,'test',{now:()=>clock,process:async()=>{clock+=11000;throw Error('provider unavailable')}});assert.deepEqual(result,{checked:0,failed:2,pending:12,busy:false})});
test('reconciliation cannot read another tenant call or a billing-connected workspace',async()=>{const kv=fixture();kv.values['voice:call:call_0'].workspaceId='other';let seen=[];const result=await reconcile(kv,'test',{process:async(_,event)=>seen.push(event.call.id)});assert.equal(result.failed,1);assert.ok(!seen.includes('provider_0'));kv.values['workspace:test'].stripeCustomerId='cus_test';await assert.rejects(reconcile(kv,'test'))});

test('persistent failures rotate across the queue and publish safe recovery diagnostics',async()=>{const kv=fixture(),seen=[];const process=async(_,event)=>{seen.push(event.call.id);throw Error('sensitive transport details')};await reconcile(kv,'test',{process,now:()=>1000});await reconcile(kv,'test',{process,now:()=>2000});assert.deepEqual(seen,Array.from({length:10},(_,i)=>'provider_'+i));assert.equal(kv.values['voice:recovery:test'].state,'attention');assert.equal(kv.values['voice:recovery:test'].lastRunAt,2000);assert.equal(Object.keys(kv.values['voice:pending:test']).length,12);assert.ok(!JSON.stringify(kv.values['voice:recovery:test']).includes('sensitive'));assert.equal(kv.values['audit:test'].length,2)});

test('concurrent reconciliation does not start another provider batch',async()=>{const kv=fixture();let release,started=0;const first=reconcile(kv,'test',{process:async()=>{if(started++===0)await new Promise(resolve=>release=resolve)}});while(!release)await new Promise(resolve=>setImmediate(resolve));const second=await reconcile(kv,'test',{process:()=>assert.fail('overlapping provider request')});assert.equal(second.busy,true);release();kv.values['voice:pending:test']={};await first;assert.equal(kv.values['voice:reconcile-lock:test'],undefined)});

test('targeted event recovery does not advance the fair queue cursor',async()=>{const kv=fixture();kv.values['voice:recovery:test']={cursor:'call_4'};const seen=[];await reconcile(kv,'test',{callId:'call_9',process:async(_,event)=>seen.push(event.call.id)});assert.deepEqual(seen,['provider_9']);assert.equal(kv.values['voice:recovery:test'].cursor,'call_4')});

test('a replaced lease is not deleted by the prior worker',async()=>{const kv=fixture();await reconcile(kv,'test',{process:async()=>{kv.values['voice:reconcile-lock:test']='new-worker'}});assert.equal(kv.values['voice:reconcile-lock:test'],'new-worker')});

test('malformed queue fails closed and releases its lease',async()=>{const kv=fixture();kv.values['voice:pending:test']=[];await assert.rejects(reconcile(kv,'test'));assert.equal(kv.values['voice:reconcile-lock:test'],undefined)});
