const test=require('node:test'),assert=require('node:assert/strict'),{voiceNotifications}=require('../lib/voice-notifications');
const call={id:'voice_one',source:'phone',createdAt:1000,caller:'Alex',reason:'Sink still leaks',disposition:'message_taken',category:'Complaint'};
test('saved phone requests produce stable specific call links; replay does not change identity',()=>{const first=voiceNotifications([call]);assert.equal(first.length,1);assert.deepEqual(first[0].meta,{callId:'voice_one'});assert.equal(first[0].view,'calls');assert.equal(first[0].createdAt,1000);assert.deepEqual(voiceNotifications([call]),first)});
test('resolved, noncustomer, website and completed calls do not produce request alerts',()=>{assert.deepEqual(voiceNotifications([{...call,disposition:'resolved_by_ai'},{...call,disposition:'non_customer'},{...call,source:'website'}]),[]);for(const status of ['completed','dismissed','no_action'])assert.deepEqual(voiceNotifications([call],{voice_one:{status}}),[])});
test('corrupt team state fails rather than falsely hiding phone requests',()=>{assert.throws(()=>voiceNotifications([call],[]));assert.throws(()=>voiceNotifications([call],{voice_one:null}));assert.throws(()=>voiceNotifications([{...call,createdAt:'invalid'}]))});
test('request notifications select the latest twenty calls and respect priority',()=>{const calls=Array.from({length:30},(_,i)=>({...call,id:'voice_'+i,createdAt:i,reason:i===29?'urgent gas concern':'Callback request'}));const result=voiceNotifications(calls);assert.equal(result.length,20);assert.equal(result[0].meta.callId,'voice_29');assert.equal(result[0].kind,'warning');assert.equal(result[19].meta.callId,'voice_10')});

const vm=require('node:vm'),fs=require('node:fs');
async function builtNotifications(state,notifyCalls=true){
 const api=fs.readFileSync('api/account.js','utf8'),start=api.indexOf('async function buildClientNotifications('),end=api.indexOf('\nasync function buildAdminNotifications(',start);
 const values={'workspace:tenant':{id:'tenant',plan:'starter'},'settings:tenant':{notifyCalls,notifySetup:false},'agent:tenant':{},'phone:index':[],'calls:tenant':[call],'support:index':[],'feedback:tenant':[],'followup:state:tenant':state};
 const ctx=vm.createContext({kv:{get:async k=>values[k]??null},entitlementsFor:()=>({minutes:300}),aiFeedbackListForWorkspace:async()=>({items:[],sourceValid:true}),aiFeedbackWorkspaceIndexKey:id=>'feedback:'+id,notificationItem:(id,item)=>({...item,id}),require:p=>{assert.equal(p,'../lib/voice-notifications');return {voiceNotifications}},Date,Set,Number,String,Array});
 vm.runInContext(api.slice(start,end),ctx);return vm.runInContext('buildClientNotifications({workspaceId:"tenant"})',ctx);
}
test('notification API builds the exact call alert and honors the client preference',async()=>{const result=await builtNotifications({});assert.equal(result.items.length,1);assert.equal(result.items[0].meta.callId,'voice_one');assert.equal(result.coverage.limited,false);assert.equal((await builtNotifications({},false)).items.length,0)});
test('notification API preserves unavailable coverage when follow-up state cannot be trusted',async()=>{const result=await builtNotifications({voice_one:null});assert.equal(result.items.length,0);assert.equal(result.coverage.limited,true);assert.ok(result.coverage.sources.includes('voice_followups_unavailable'))});
