const test=require('node:test'),assert=require('node:assert/strict');
const {recoverAfterEvent,maintenance}=require('../lib/voice-recovery');
const {revision}=require('../lib/voice-policy');
const env={VERCEL_ENV:'preview',CALLERCORE_VOICE_PREVIEW_ENABLED:'true',VAPI_INTERNAL_ASSISTANT_ID:'internal',VAPI_DEMO_ASSISTANT_ID:'demo',VAPI_INTERNAL_NUMBER_ID:'number_internal',VAPI_DEMO_NUMBER_ID:'number_demo'};
function fixture(){const id='voice_'+revision('provider_call').slice(0,24),values=new Map([['voice:call:'+id,{workspaceId:'test',status:'ended'}],['workspace:test',{voiceTestWorkspace:true}],['voice:pending:test',{[id]:true}]]);return {id,values,get:async key=>structuredClone(values.get(key)),set:async(key,value,{nx})=>{if(nx&&values.has(key))return null;values.set(key,value);return 'OK'}}}
test('ended-event recovery retries twice without changing CRM outside the canonical processor',async()=>{const kv=fixture(),delays=[],calls=[];const result=await recoverAfterEvent(kv,'provider_call',{env,sleep:async ms=>delays.push(ms),run:async(_,ws,opts)=>calls.push({ws,...opts})});assert.deepEqual(delays,[2000,8000]);assert.equal(result.attempts,2);assert.deepEqual(calls,[{ws:'test',callId:kv.id},{ws:'test',callId:kv.id}]);assert.equal((await recoverAfterEvent(kv,'provider_call',{env})).scheduled,false)});
test('recovered details stop the background retries early',async()=>{const kv=fixture(),delays=[];const result=await recoverAfterEvent(kv,'provider_call',{env,sleep:async ms=>delays.push(ms),run:async()=>kv.values.set('voice:pending:test',{})});assert.equal(result.attempts,1);assert.deepEqual(delays,[2000,8000])});
test('active, customer, deleted and fully processed calls cannot launch background work',async()=>{for(const kind of ['active','customer','deleted','complete']){const kv=fixture();if(kind==='active')kv.values.get('voice:call:'+kv.id).status='active';if(kind==='customer')kv.values.get('workspace:test').stripeCustomerId='cus';if(kind==='deleted')kv.values.get('workspace:test').deletedAt=1;if(kind==='complete')kv.values.set('voice:pending:test',{});assert.equal((await recoverAfterEvent(kv,'provider_call',{env,sleep:()=>assert.fail('not authorized'),run:()=>assert.fail('not authorized')})).scheduled,false)}});
test('maintenance is Preview-only, uses designated bindings and isolates workspace failure',async()=>{const kv=fixture();kv.values.set('voice:binding:internal',{workspaceId:'test',provider:'vapi',purpose:'internal',numberId:'number_internal'});kv.values.set('voice:binding:demo',{workspaceId:'demo-test',provider:'vapi',purpose:'demo',numberId:'number_demo'});const seen=[];const result=await maintenance(kv,{env,run:async(_,id)=>{seen.push(id);if(id==='demo-test')throw Error('provider private details');return {checked:2,failed:0,pending:0,busy:false}}});assert.deepEqual(seen,['test','demo-test']);assert.deepEqual(result,{workspaces:2,checked:2,failed:1,busy:false,pending:null});assert.ok(!JSON.stringify(result).includes('private'));await assert.rejects(maintenance(kv,{env:{...env,VERCEL_ENV:'production'}}))});
test('maintenance ignores disabled, unrecognized and unconfigured resource bindings',async()=>{const kv=fixture();kv.values.set('voice:binding:internal',{workspaceId:'test',provider:'vapi',purpose:'internal',numberId:'number_internal',disabled:true});kv.values.set('voice:binding:demo',{workspaceId:'test',provider:'other',purpose:'demo'});assert.equal((await maintenance(kv,{env,run:()=>assert.fail('invalid binding')})).workspaces,0)});
